name: GH Actions - Release
on:
  workflow_run:
    workflows:
      - 'GH Actions - Lint'
      - 'GH Actions - Test'
    branches:
      - 'main'
      - 'v*.x.x'
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Release
      run: yarn semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.PORYGON_Y_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
